# Generated by Django 3.0.2 on 2020-01-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('I', 'La amenaza fantasma'), ('II', 'El ataque de los clones'), ('III', 'La venganza de los Sith'), ('IV', 'Una nueva esperanza'), ('V', 'El Imperio contraataca'), ('VI', 'Return of the Jedi'), ('VII', 'El despertar de la Fuerza'), ('VIII', 'Los últimos Jedi'), ('IX', 'El ascenso de Skywalker')], default='I', help_text='select a options', max_length=4)),
                ('opening_text', models.TextField(help_text='insert the text opening', max_length=1000)),
                ('director', models.CharField(help_text="Enter the director's name", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_character', models.CharField(help_text="Enter the chracter's name", max_length=50)),
                ('actor', models.CharField(blank=True, help_text='Enter the real name of the chracter', max_length=50)),
                ('performances', models.ManyToManyField(help_text='select the movies in which the character appears', to='film.Film')),
            ],
        ),
    ]
