# Generated by Django 3.0.2 on 2020-01-22 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_personage', models.CharField(help_text="Enter the personage's name", max_length=50)),
                ('actor', models.CharField(blank=True, help_text='Enter the real name of the personage', max_length=50)),
                ('performances', models.ManyToManyField(help_text='select the movies in which the personage appears', to='film.Film')),
            ],
        ),
        migrations.DeleteModel(
            name='Character',
        ),
        migrations.AddField(
            model_name='film',
            name='pesonage',
            field=models.ManyToManyField(blank=True, help_text='select the personages', to='film.Personage'),
        ),
    ]
