# Generated by Django 3.0.2 on 2020-01-22 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_auto_20200121_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='pesonage',
        ),
    ]
