# Generated by Django 3.0.2 on 2020-01-22 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0003_remove_film_pesonage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(help_text='select a options', max_length=40),
        ),
    ]
