# Generated by Django 3.0.2 on 2020-01-24 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0004_auto_20200122_0019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_planet', models.CharField(help_text="Enter the personage's name", max_length=50)),
                ('appearances', models.ManyToManyField(to='film.Film')),
            ],
        ),
    ]
